# Generated by Django 3.2.8 on 2022-08-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=3000)),
                ('testSteps', models.TextField(blank=True, max_length=3000, null=True)),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('lastName', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=250)),
                ('password', models.TextField(max_length=200)),
                ('username', models.TextField(max_length=30)),
                ('roleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.role')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTapi.test')),
                ('testerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTapi.project')),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.status')),
            ],
        ),
        migrations.CreateModel(
            name='TestObjective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.status')),
                ('testPlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTapi.testplan')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='testObjectiveId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTapi.testobjective'),
        ),
        migrations.AddField(
            model_name='test',
            name='testerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.user'),
        ),
    ]
