# Generated by Django 3.1.3 on 2022-08-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='statusId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.status'),
        ),
        migrations.AlterField(
            model_name='testobjective',
            name='statusId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTapi.status'),
        ),
    ]
